<a href="https://colab.research.google.com/github/driano1221/ControleEst/blob/main/UntitledPAULO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [125]:
import pandas as pd

# Substitua 'Base de dados - MEQ - Onda 5.csv' pelo caminho correto do arquivo
file_path = 'Base de dados - MEQ - Onda 5 (3).csv'

try:
    # Lê o arquivo CSV com o separador correto
    df = pd.read_csv(file_path, sep=';')

    # Lista das variáveis onde 6 deve ser substituído por NA
    vars_6_to_na = ['P3', 'P7', 'P10', 'P12', 'P13', 'P14', 'P181', 'P182']

    # Lista das variáveis onde 3 deve ser substituído por NA
    vars_3_to_na = ['P171', 'P172', 'P173', 'P174', 'P175', 'P176', 'P177', 'P178', 'P179']

    # Substituir 6 por NA nas variáveis especificadas
    for var in vars_6_to_na:
        df[var] = df[var].replace(6, pd.NA)

    # Substituir 3 por NA nas variáveis especificadas
    for var in vars_3_to_na:
        df[var] = df[var].replace(3, pd.NA)

    # Primeiro substituir 'D' por 'C' na variável P30
    df['P30'] = df['P30'].replace('D', 'C')

    # Depois converter A=1, B=2, C=3 na variável P30
    df['P30'] = df['P30'].replace({'A': 1, 'B': 2, 'C': 3})

    # Verificar as mudanças
    print("Mudanças realizadas com sucesso!")
    print("\nValores únicos em P30:", df['P30'].unique())

    # Opcional: salvar o DataFrame modificado em um novo arquivo
    # df.to_csv('Base de dados - MEQ - Onda 5 - modificado.csv', sep=';', index=False)

except FileNotFoundError:
    print(f"Erro: Arquivo '{file_path}' não encontrado.")
except pd.errors.ParserError:
    print(f"Erro: Não foi possível analisar o arquivo '{file_path}'. Verifique se o separador está correto.")
except Exception as e:
    print(f"Ocorreu um erro inesperado: {e}")

Mudanças realizadas com sucesso!

Valores únicos em P30: [1 2 3]

<ipython-input-125-7c131270271c>:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['P30'] = df['P30'].replace({'A': 1, 'B': 2, 'C': 3})

In [126]:
# Verificação das mudanças (opcional)
for var in vars_6_to_na:
    print(f"\nValores únicos em {var}:", df[var].unique())

for var in vars_3_to_na:
    print(f"\nValores únicos em {var}:", df[var].unique())

print("\nValores únicos em P30:", df['P30'].unique())

Valores únicos em P3: [3 1 <NA> 4 2 5]

Valores únicos em P7: [2 1 5 4 <NA> 3]

Valores únicos em P10: [2 5 3 1 4 <NA>]

Valores únicos em P12: [5 4 2 3 1 <NA>]

Valores únicos em P13: [3 2 1 4 5 <NA>]

Valores únicos em P14: [2 5 4 3 1 <NA>]

Valores únicos em P181: [5 4 3 2 1 <NA>]

Valores únicos em P182: [3 5 4 2 1 <NA>]

Valores únicos em P171: [1 <NA> 2]

Valores únicos em P172: [2 1 <NA>]

Valores únicos em P173: [2 1 <NA>]

Valores únicos em P174: [2 1 <NA>]

Valores únicos em P175: [1 <NA> 2]

Valores únicos em P176: [1 2 <NA>]

Valores únicos em P177: [2 1 <NA>]

Valores únicos em P178: [<NA> 1 2]

Valores únicos em P179: [1 <NA> 2]

Valores únicos em P30: [1 2 3]

In [127]:
df['Peso'].describe()

count     1520
unique      89
top       0,12
freq        60
Name: Peso, dtype: object

In [128]:

df['P30'] = df['P30'].replace({'A': 1, 'B': 2, 'C': 3})
df
print(df['P30'].describe())

count    1520.000000
mean        2.279605
std         0.815489
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         3.000000
Name: P30, dtype: float64

In [129]:
import pandas as pd

dicionario = {
    "F2": {
        "Feminino": 1,
        "Masculino": 2
    },
    "F3": {
        "Centro-Oeste" : 1,
        "Nordeste" : 2,
        "Norte" : 3,
        "Sudeste" : 4,
        "Sul" : 5
    },
    "F6": {
        "18 a 24 anos" : 1,
        "25 a 34 anos" : 2,
        "35 a 44 anos" : 3,
        "45 a 64 anos" : 4
    },
    "P0,1": {
        "Algumas vezes por mês" : 3,
        "Não faço isso" : 5,
        "Pelo menos 3 vezes por semana" : 2,
        "Raramente" : 4,
        "Todos os dias" : 1

    },
    "P0,2": {
        "Algumas vezes por mês" : 3,
        "Não faço isso" : 5,
        "Pelo menos 3 vezes por semana" : 2,
        "Raramente" : 4,
        "Todos os dias" : 1

    },
    "P0,3": {
        "Algumas vezes por mês" : 3,
        "Não faço isso" : 5,
        "Pelo menos 3 vezes por semana" : 2,
        "Raramente" : 4,
        "Todos os dias" : 1

    },
    "P0,4": {
        "Algumas vezes por mês" : 3,
        "Não faço isso" : 5,
        "Pelo menos 3 vezes por semana" : 2,
        "Raramente" : 4,
        "Todos os dias" : 1

    },
    "P0,5": {
        "Algumas vezes por mês" : 3,
        "Não faço isso" : 5,
        "Pelo menos 3 vezes por semana" : 2,
        "Raramente" : 4,
        "Todos os dias" : 1

    },
    "P1": {
        "Não, nunca ouvi falar" : 3,
        "Sim" : 1,
        "Talvez, mas não tenho certeza" : 2

    },
    "P3": {
        "Concordo totalmente" : 5,
        "Discordo Totalmente" : 1,
        "Concordo em parte" : 4,
        "Discordo em parte" : 2,
        "Não sei avaliar" : "NA",
        "Nem concordo, nem discordo" : 3
    },
    "P5": {
        "A" : 1,
        "B" : 2,
        "C" : 3,
        "D" : 4,
        "E" : 5
    },
    "P7": {
        "1 - Muito prejudiciais" : 1,
        "2 - Pouco prejudiciais" : 2,
        "3 - Indiferente" : 3,
        "4 - Pouco benéficos" : 4,
        "5 - Muito Benéficos" : 5,
        "Não sei avaliar" : "NA"


    },
    "P30": {
        "A" : 1,
        "B" : 2,
        "C" : 3,
        "D" : "NA"
    },
    "P10": {
        "1 - Muito prejudiciais" : 1,
        "2 - Pouco prejudiciais" : 2,
        "3 - Indiferente" : 3,
        "4 - Pouco benéficos" : 4,
        "5 - Muito Benéficos" : 5,
        "Não sei avaliar" : "NA"


    },
    "P11": {
        "BP" : 1,
        "Equinor" : 2,
        "Nenhuma dessa lista" : 3,
        "Petrobras" : 4,
        "Shell" : 5,
        "Sou indiferente" : 7,
        "TotalEnergies" : 8


    },
    "P12": {
        "Concordo totalmente" : 5,
        "Discordo Totalmente" : 1,
        "Concordo em parte" : 4,
        "Discordo em parte" : 2,
        "Não sei avaliar" : "NA",
        "Nem concordo, nem discordo" : 3
    },
    "P13": {
        "Concordo totalmente" : 5,
        "Discordo Totalmente" : 1,
        "Concordo em parte" : 4,
        "Discordo em parte" : 2,
        "Não sei avaliar" : "NA",
        "Nem concordo, nem discordo" : 3
    },
    "P14": {
        "Concordo totalmente" : 5,
        "Discordo Totalmente" : 1,
        "Concordo em parte" : 4,
        "Discordo em parte" : 2,
        "Não sei avaliar" : "NA",
        "Nem concordo, nem discordo" : 3
    },
    "P17,1": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,2": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,3": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,4": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,5": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,6": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,7": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,8": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P17,9": {
        "Confio" : 1,
        "Não confio" : 2,
        "Não sei" : "NA"
    },
    "P18,1": {
        "Concordo totalmente" : 5,
        "Discordo Totalmente" : 1,
        "Concordo em parte" : 4,
        "Discordo em parte" : 2,
        "Não sei avaliar" : "NA",
        "Nem concordo, nem discordo" : 3
    },
    "P18,2": {
        "Concordo totalmente" : 5,
        "Discordo Totalmente" : 1,
        "Concordo em parte" : 4,
        "Discordo em parte" : 2,
        "Não sei avaliar" : "NA",
        "Nem concordo, nem discordo" : 3
    }
}

base = pd.read_excel("base_python (1).xlsx")

for coluna, substituicoes in dicionario.items():
    if coluna in base.columns:
        base[coluna] = base[coluna].replace(substituicoes)

<ipython-input-129-3dc36061398f>:210: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  base[coluna] = base[coluna].replace(substituicoes)

In [130]:
base.columns

Index(['ID de resposta', 'Endereço de IP', 'Variável Personalizada 1', 'RID',
       'UF_0', 'UF', 'F3', 'F6', 'F2', 'F7', 'P30', 'P0,1', 'P0,2', 'P0,3',
       'P0,4', 'P0,5', 'P1', 'P2', 'P3', 'P5', 'P7', 'P8', 'P8_1', 'P8_2',
       'P8_3', 'P8_4', 'P8_5', 'P8_6', 'P8_7', 'P8_8', 'P8_9', 'P8_97',
       'P8_99', 'P9_1', 'P9_2', 'P9_3', 'P9_4', 'P9_5', 'P9_6', 'P9_7',
       'P9_97', 'P9_99', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'P17,1',
       'P17,2', 'P17,3', 'P17,4', 'P17,5', 'P17,6', 'P17,7', 'P17,8', 'P17,9',
       'P18,1', 'P18,2', 'P21', 'P22', 'P23', 'P26', 'P27', 'Peso'],
      dtype='object')

In [131]:
# prompt: mostar head das primeiras 10 variáveis de base, e  depois mostrar o summary da coluna Peso

print(base.head(10))
print("\nSummary da coluna 'Peso':")
print(base['Peso'].describe())

   ID de resposta                          Endereço de IP  \
0       150052588                          191.241.129.94
1       150052636                          45.161.152.233
2       150052711   2804:d47:6605:d00:3fb3:b783:7aaa:300f
3       150052712                           201.1.219.105
4       150052810  2804:1b3:a1c0:55b1:d79e:9bbe:b2c8:a02e
5       150052813  2804:14d:68b0:8186:20a3:94ec:ef48:6b5d
6       150052869                           168.0.148.175
7       150052894                          177.192.23.167
8       150052956                           179.106.81.68
9       150052966    2804:1eb0:c0:c9f:8c56:5b49:2b3f:805a

   Variável Personalizada 1                                   RID UF_0  \
0                      31.0  6745f60b-56b6-68ee-0a8e-8961b5e89bc1   SE
1                      54.0  6745f620-e646-561b-a76e-9301c79fc842   RJ
2                      43.0  6745f640-48e5-f687-edf1-52b57f4d3ec3   SE
3                      44.0  6745f644-4b12-9488-8031-61b0274f3844   SP
4                      48.0  6745f65c-c38b-cfe1-7472-34ec156585c8   SP
5                      28.0  6745f674-39ed-cf41-5720-4a0cee9ea5e4   SP
6                      49.0  6745f685-4b49-7369-0302-6f290dd309b8   RS
7                      36.0  6745f67e-bd14-85f0-18d0-47dda85d4559   RJ
8                      21.0  6745f6b2-4aa0-8f4b-2d46-22eb5c85c08c   MG
9                      34.0  6745f6af-ecc7-7add-a3b8-f61b1bc54968   CE

                  UF  F3  F6  F2  F7  ...  P17,8  P17,9  P18,1  P18,2  \
0            Sergipe   2   3   1   7  ...      1      2      2      1
1     Rio de Janeiro   4   2   1   7  ...      2      1      3      4
2            Sergipe   2   3   2   8  ...     NA      2      4      2
3          São Paulo   4   4   1   7  ...      2      1      5      5
4          São Paulo   4   3   1   8  ...      1      2      5      4
5          São Paulo   4   4   1   4  ...      1      1      5      4
6  Rio Grande do Sul   5   2   2   7  ...      2      1      2      4
7     Rio de Janeiro   4   3   1   7  ...      1      1      4      3
8       Minas Gerais   4   3   1   7  ...      2     NA      3      4
9              Ceará   2   2   1   7  ...      1      2      5      5

                                                 P21        P22       P23  \
0                             Nenhuma das anteriores   Feminino   Sudeste
1                             Nenhuma das anteriores   Feminino   Sudeste
2                             Nenhuma das anteriores  Masculino       Sul
3  Área financeira (bancos, seguradoras, financei...  Masculino   Sudeste
4                             Nenhuma das anteriores   Feminino       Sul
5                             Nenhuma das anteriores   Feminino   Sudeste
6                             Nenhuma das anteriores  Masculino  Nordeste
7  Área financeira (bancos, seguradoras, financei...   Feminino   Sudeste
8                             Nenhuma das anteriores   Feminino   Sudeste
9                             Nenhuma das anteriores   Feminino   Sudeste

            P26                                  P27  Peso
0  25 a 34 anos             ensino superior completo  0.75
1  35 a 44 anos  pós-graduação / mestrado/ doutorado  0.15
2  25 a 34 anos             ensino superior completo  0.49
3  35 a 44 anos             ensino superior completo  1.29
4  35 a 44 anos             ensino superior completo  0.15
5  25 a 34 anos             ensino superior completo  1.78
6  25 a 34 anos             ensino superior completo  0.24
7  35 a 44 anos             ensino superior completo  0.62
8  25 a 34 anos  pós-graduação / mestrado/ doutorado  2.06
9  25 a 34 anos             ensino superior completo  1.04

[10 rows x 65 columns]

Summary da coluna 'Peso':
count    1510.000000
mean        0.992305
std         0.901660
min         0.020000
25%         0.250000
50%         0.730000
75%         1.620000
max         4.780000
Name: Peso, dtype: float64

In [132]:
print(base['P30'].describe())

count    1510.000000
mean        2.278146
std         0.816163
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         3.000000
Name: P30, dtype: float64

In [133]:
# Renomear P01 até P05
df = df.rename(columns={
    'P01': 'P0.1',
    'P02': 'P0.2',
    'P03': 'P0.3',
    'P04': 'P0.4',
    'P05': 'P0.5',
    'P171': 'P17.1',
    'P172': 'P17.2',
    'P173': 'P17.3',
    'P174': 'P17.4',
    'P175': 'P17.5',
    'P176': 'P17.6',
    'P177': 'P17.7',
    'P178': 'P17.8',
    'P179': 'P17.9',
    'P181': 'P18.1',
    'P182': 'P18.2'
})

In [134]:
# Renomear as variáveis
base = base.rename(columns={
    'ID de resposta': 'ID',
    'P0,1': 'P0.1',
    'P0,2': 'P0.2',
    'P0,3': 'P0.3',
    'P0,4': 'P0.4',
    'P0,5': 'P0.5',
    'P17,1': 'P17.1',
    'P17,2': 'P17.2',
    'P17,3': 'P17.3',
    'P17,4': 'P17.4',
    'P17,5': 'P17.5',
    'P17,6': 'P17.6',
    'P17,7': 'P17.7',
    'P17,8': 'P17.8',
    'P17,9': 'P17.9',
    'P18,1': 'P18.1',
    'P18,2': 'P18.2'
})

In [135]:
# Criar coluna identificadora em cada base
df['Onda'] = 5
base['Onda'] = 6

# Concatenar as bases
base_completa = pd.concat([df, base], ignore_index=True)

In [138]:
base_completa["P18.2"].unique()

array([3, 5, 4, 2, 1, <NA>, 'NA'], dtype=object)

In [139]:
# prompt: nome colunas da base_completa

base_completa.columns

Index(['ID', 'UF', 'F3', 'F6', 'F2', 'P30', 'Peso', 'F7', 'F8', 'F9', 'P0.1',
       'P0.2', 'P0.3', 'P0.4', 'P0.5', 'P1', 'P2', 'P3', 'P5', 'P7', 'P10',
       'P11', 'P12', 'P13', 'P14', 'P15', 'P17.1', 'P17.2', 'P17.3', 'P17.4',
       'P17.5', 'P17.6', 'P17.7', 'P17.8', 'P17.9', 'P18.1', 'P18.2', 'P8_1',
       'P8_2', 'P8_3', 'P8_4', 'P8_5', 'P8_6', 'P8_7', 'P8_8', 'P8_9', 'P9_1',
       'P9_2', 'P9_3', 'P9_4', 'P9_5', 'P9_6', 'P9_7', 'P83', 'P81', 'P84',
       'P82', 'P85', 'P86', 'P87', 'P88', 'P89', 'P91', 'P92', 'P93', 'P94',
       'P95', 'P96', 'P97', 'Onda', 'Endereço de IP',
       'Variável Personalizada 1', 'RID', 'UF_0', 'P8', 'P8_97', 'P8_99',
       'P9_97', 'P9_99', 'P21', 'P22', 'P23', 'P26', 'P27'],
      dtype='object')

In [140]:
variaveis_manter = [
    'P30',
    'ID',  # Identificador
    'UF',  # Unidade Federativa
    'F2',  # Gênero
    'F3',  # Região do país
    'F6',  # Idade
    'P0.1', # Frequência assistir noticiário TV
    'P0.2', # Frequência ler notícias internet
    'P0.3', # Frequência acessar redes sociais
    'P0.4', # Frequência ouvir notícias rádio
    'P0.5', # Frequência ler jornais e revistas
    'P1',   # Conhecimento sobre Margem Equatorial
    'P3',   # Conhecimento sobre projetos Margem Equatorial
    'P5',   # Questão sobre o mapa
    'P7',   # Efeitos socioambientais
    'P8_1', # Poluição rios
    'P8_2', # Poluição florestas
    'P8_3', # Prejuízo pesca
    'P8_4', # Riscos vida marinha
    'P8_5', # Riscos corais
    'P8_6', # Prejuízos comunidades locais
    'P8_7', # Prejuízos povos indígenas
    'P8_8', # Riscos países vizinhos
    'P8_9', # Nenhum efeito negativo
    'P9_1', # Construção hospitais
    'P9_2', # Construção escolas
    'P9_3', # Melhoria infraestrutura
    'P9_4', # Apoio projetos ambientais
    'P9_5', # Oferta emprego
    'P9_6', # Atração investimentos
    'P9_7', # Nenhum efeito positivo
    'P10',  # Efeitos econômicos
    'P11',  # Preferência empresa
    'P12',  # Expertise Petrobras
    'P13',  # Preocupação socioambiental Petrobras
    'P14',  # Contribuição desenvolvimento
    'P15',  # Importância investimento
    'P17.1', # Confiança Ministério Meio Ambiente
    'P17.2', # Confiança IBAMA
    'P17.3', # Confiança Petrobras
    'P17.4', # Confiança Ministério Minas e Energia
    'P17.5', # Confiança STF
    'P17.6', # Confiança Governo Federal
    'P17.7', # Confiança Governos estaduais
    'P17.8', # Confiança Greenpeace
    'P17.9', # Confiança empresas petrolíferas estrangeiras
    'P18.1', # Capacidade Petrobras explorar com segurança
    'P18.2', # Benefícios justificam investimento
    'Peso',  # Peso amostral
    'Onda'   # Identificador da onda
]

# Para filtrar a base apenas com essas variáveis:
base_filtrada = base_completa[variaveis_manter]

In [141]:
base_filtrada

,P30,ID,UF,F2,F3,F6,P0.1,P0.2,P0.3,P0.4,...,P17.4,P17.5,P17.6,P17.7,P17.8,P17.9,P18.1,P18.2,Peso,Onda
0,1,403,7,1,1,1,4,4,1,5,...,2,1,1,2,<NA>,1,5,3,"0,14",5
1,1,602,9,1,1,1,5,1,1,5,...,1,1,1,1,1,<NA>,4,5,"0,14",5
2,1,516,9,1,1,1,3,2,2,4,...,<NA>,<NA>,1,2,<NA>,2,4,4,"0,14",5
3,1,2927,7,1,1,1,1,1,1,2,...,1,<NA>,1,1,1,<NA>,3,2,"0,14",5
4,2,210,12,1,1,1,1,1,1,4,...,2,2,2,2,1,2,2,2,"0,56",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3025,3,151776882,Goiás,2,1,4,1,1,1,1,...,2,2,1,2,2,1,5,5,2.07,6
3026,1,151776928,Distrito Federal,1,1,2,1,1,1,1,...,NA,1,1,NA,1,2,5,3,0.08,6
3027,1,151777090,Santa Catarina,2,5,4,1,1,1,3,...,2,2,2,2,1,2,5,5,0.1,6
3028,3,151777439,Amapá,2,3,1,2,1,2,3,...,2,NA,1,1,1,NA,4,4,0.31,6
3029,1,151778884,Pará,2,3,1,2,1,1,4,...,1,1,1,1,1,2,5,3,0.04,6

In [142]:
import pandas as pd
import numpy as np
grupos_analise = {
    'Feminino': {'variavel': 'F2', 'valor': 1, 'descricao': 'feminino'},
    'Masculino': {'variavel': 'F2', 'valor': 2, 'descricao': 'masculino'},
    'Centro_Oeste': {'variavel': 'F3', 'valor': 1, 'descricao': 'Centro-Oeste'},
    'Nordeste': {'variavel': 'F3', 'valor': 2, 'descricao': 'Nordeste'},
    'Norte': {'variavel': 'F3', 'valor': 3, 'descricao': 'Norte'},
    'Sudeste': {'variavel': 'F3', 'valor': 4, 'descricao': 'Sudeste'},
    'Sul': {'variavel': 'F3', 'valor': 5, 'descricao': 'Sul'},
    'ClasseA': {'variavel': 'P30', 'valor': 1, 'descricao': 'A'},
    'ClasseB': {'variavel': 'P30', 'valor': 2, 'descricao': 'B'},
    'ClasseC': {'variavel': 'P30', 'valor': 3, 'descricao': 'C'},
    'Idade_18_24': {'variavel': 'F6', 'valor': 1, 'descricao': '18 a 24 anos'},
    'Idade_25_34': {'variavel': 'F6', 'valor': 2, 'descricao': '25 a 34 anos'},
    'Idade_35_44': {'variavel': 'F6', 'valor': 3, 'descricao': '35 a 44 anos'},
    'Idade_45_64': {'variavel': 'F6', 'valor': 4, 'descricao': '45 a 64 anos'}
}
# Lista de variáveis para análise
variaveis = [
    'F2', 'F3', 'F6',
    'P0.1', 'P0.2', 'P0.3', 'P0.4', 'P0.5',
    'P1', 'P3', 'P5', 'P7',
    'P8_1', 'P8_2', 'P8_3', 'P8_4', 'P8_5', 'P8_6', 'P8_7', 'P8_8', 'P8_9',
    'P9_1', 'P9_2', 'P9_3', 'P9_4', 'P9_5', 'P9_6', 'P9_7',
    'P10', 'P11', 'P12', 'P13', 'P14', 'P15',
    'P17.1', 'P17.2', 'P17.3', 'P17.4', 'P17.5', 'P17.6', 'P17.7', 'P17.8', 'P17.9',
    'P18.1', 'P18.2','P30'
]

# Função para calcular estatísticas
def calcular_estatisticas(df, variaveis):
    resultados = []

    for var in variaveis:
        for onda in df['Onda'].unique():
            dados_onda = df[df['Onda'] == onda]

            dados_onda[var] = pd.to_numeric(dados_onda[var], errors='coerce')

            n = dados_onda[var].count()
            media = dados_onda[var].mean()
            desvio = dados_onda[var].std()
            erro_padrao = desvio / np.sqrt(n) if n > 0 else np.nan

            resultados.append({
                'Variavel': var,
                'Onda': f"{onda}ª - Geral",
                'N': n,
                'Media': media,
                'Desvio': desvio,
                'Erro_Padrao': erro_padrao
            })

    return pd.DataFrame(resultados)

# Calcular estatísticas
estatisticas = calcular_estatisticas(base_filtrada, variaveis)

# Exibir resultados
print(estatisticas)

# Salvar em Excel
estatisticas.to_excel('estatisticas_por_ondag.xlsx', index=False)

   Variavel        Onda     N     Media    Desvio  Erro_Padrao
0        F2  5ª - Geral  1520  1.446711  0.497316     0.012756
1        F2  6ª - Geral  1510  1.450331  0.497692     0.012808
2        F3  5ª - Geral  1520  3.196711  1.240682     0.031823
3        F3  6ª - Geral  1510  3.190728  1.244490     0.032026
4        F6  5ª - Geral  1520  2.618421  1.025252     0.026297
..      ...         ...   ...       ...       ...          ...
87    P18.1  6ª - Geral  1474  3.938942  1.163633     0.030309
88    P18.2  5ª - Geral  1464  3.592213  1.257527     0.032866
89    P18.2  6ª - Geral  1465  3.896246  1.127230     0.029451
90      P30  5ª - Geral  1520  2.279605  0.815489     0.020917
91      P30  6ª - Geral  1510  2.278146  0.816163     0.021003

[92 rows x 6 columns]

<ipython-input-142-23b07a787649>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_onda[var] = pd.to_numeric(dados_onda[var], errors='coerce')

In [143]:
from scipy import stats
import numpy as np

def realizar_testes(df, variaveis):
    resultados = []

    for var in variaveis:
        # Separar dados por onda
        grupo5 = df[df['Onda'] == 5][var].dropna()
        grupo6 = df[df['Onda'] == 6][var].dropna()
        grupo5 = pd.to_numeric(grupo5, errors='coerce')
        grupo6 = pd.to_numeric(grupo6, errors='coerce')
        # Teste de Levene para igualdade de variâncias
        try:  # Added try-except block
            levene_stat, levene_p = stats.levene(grupo5, grupo6)
        except ValueError:
            levene_stat, levene_p = np.nan, np.nan  # Assign NaN if Levene's test fails

        # Cálculos comuns
        n1, n2 = len(grupo5), len(grupo6)
        diff_media = grupo5.mean() - grupo6.mean()

        # Para variâncias iguais
        gl_equal = n1 + n2 - 2
        s_p = np.sqrt(((n1-1)*grupo5.var() + (n2-1)*grupo6.var()) / (n1+n2-2))
        se_diff_equal = s_p * np.sqrt(1/n1 + 1/n2)
        t_stat_equal = diff_media / se_diff_equal if se_diff_equal != 0 else np.nan  # Handle division by zero
        p_value_equal = 2 * (1 - stats.t.cdf(abs(t_stat_equal), gl_equal)) if not np.isnan(t_stat_equal) else np.nan # Handle NaN t-statistic

        # Para variâncias diferentes (Welch's t-test)
        # Check for conditions that lead to NaN before calculation
        if (grupo5.var()/n1)**2/(n1-1) + (grupo6.var()/n2)**2/(n2-1) == 0 or np.isnan((grupo5.var()/n1)**2/(n1-1) + (grupo6.var()/n2)**2/(n2-1)) :
            gl_unequal = np.nan #Assign NaN if denominator is zero or NaN
        else:
            gl_unequal = int(((grupo5.var()/n1 + grupo6.var()/n2)**2) /
                            ((grupo5.var()/n1)**2/(n1-1) + (grupo6.var()/n2)**2/(n2-1)))

        se_diff_unequal = np.sqrt(grupo5.var()/n1 + grupo6.var()/n2)
        t_stat_unequal = diff_media / se_diff_unequal if se_diff_unequal != 0 else np.nan  # Handle division by zero
        p_value_unequal = 2 * (1 - stats.t.cdf(abs(t_stat_unequal), gl_unequal)) if not np.isnan(t_stat_unequal) and not np.isnan(gl_unequal) else np.nan

        # Intervalos de confiança
        t_crit_equal = stats.t.ppf(0.975, gl_equal)
        t_crit_unequal = stats.t.ppf(0.975, gl_unequal)

        # Adicionar resultados para variâncias iguais
        resultados.append({
            'Variavel': var,
            'Tipo': 'Variâncias iguais assumidas',
            'Levene_Z': levene_stat,
            'Levene_Sig': levene_p,
            't': t_stat_equal,
            'df': gl_equal,
            'Sig_2_extremidades': p_value_equal,
            'Diferenca_media': diff_media,
            'Erro_padrao_diferenca': se_diff_equal,
            'IC_95_Inferior': diff_media - t_crit_equal * se_diff_equal,
            'IC_95_Superior': diff_media + t_crit_equal * se_diff_equal
        })

        # Adicionar resultados para variâncias diferentes
        resultados.append({
            'Variavel': var,
            'Tipo': 'Variâncias iguais não assumidas',
            'Levene_Z': None,
            'Levene_Sig': None,
            't': t_stat_unequal,
            'df': gl_unequal,
            'Sig_2_extremidades': p_value_unequal,
            'Diferenca_media': diff_media,
            'Erro_padrao_diferenca': se_diff_unequal,
            'IC_95_Inferior': diff_media - t_crit_unequal * se_diff_unequal,
            'IC_95_Superior': diff_media + t_crit_unequal * se_diff_unequal
        })

    return pd.DataFrame(resultados)

# Realizar os testes
resultados_testes = realizar_testes(base_filtrada, variaveis)

# Salvar em nova aba do mesmo arquivo Excel
with pd.ExcelWriter('estatisticas_por_ondag.xlsx', mode='a', engine='openpyxl') as writer:
    resultados_testes.to_excel(writer, sheet_name='Testes', index=False)

# Mostrar primeiros resultados
print(resultados_testes.head(10))

  Variavel                             Tipo    Levene_Z    Levene_Sig  \
0       F2      Variâncias iguais assumidas    0.040119  8.412621e-01
1       F2  Variâncias iguais não assumidas         NaN           NaN
2       F3      Variâncias iguais assumidas    0.019983  8.875932e-01
3       F3  Variâncias iguais não assumidas         NaN           NaN
4       F6      Variâncias iguais assumidas    0.052222  8.192571e-01
5       F6  Variâncias iguais não assumidas         NaN           NaN
6     P0.1      Variâncias iguais assumidas  104.557617  3.752682e-24
7     P0.1  Variâncias iguais não assumidas         NaN           NaN
8     P0.2      Variâncias iguais assumidas   10.669324  1.101416e-03
9     P0.2  Variâncias iguais não assumidas         NaN           NaN

           t    df  Sig_2_extremidades  Diferenca_media  \
0  -0.200297  3028            0.841262        -0.003621
1  -0.200296  3027            0.841262        -0.003621
2   0.132500  3028            0.894598         0.005982
3   0.132498  3027            0.894599         0.005982
4   0.014534  3028            0.988405         0.000540
5   0.014534  3027            0.988405         0.000540
6  10.828152  3028            0.000000         0.550863
7  10.833700  2962            0.000000         0.550863
8   3.266393  3028            0.001101         0.128529
9   3.266956  3021            0.001099         0.128529

   Erro_padrao_diferenca  IC_95_Inferior  IC_95_Superior
0               0.018076       -0.039063        0.031822
1               0.018076       -0.039064        0.031822
2               0.045148       -0.082541        0.094505
3               0.045148       -0.082542        0.094506
4               0.037171       -0.072343        0.073424
5               0.037171       -0.072342        0.073423
6               0.050873        0.451113        0.650612
7               0.050847        0.451163        0.650562
8               0.039349        0.051376        0.205682
9               0.039342        0.051389        0.205669

In [144]:
# Filtrar apenas sexo masculino nas duas bases
base_masculino = base_filtrada[base_filtrada['F2'] == 2].copy()

# Função para estatísticas descritivas (mantém a mesma)
def calcular_estatisticas_masculino(df, variaveis):
    resultados = []

    for var in variaveis:
        for onda in df['Onda'].unique():
            dados_onda = df[df['Onda'] == onda]
            dados_onda[var] = pd.to_numeric(dados_onda[var], errors='coerce')
            n = dados_onda[var].count()
            media = dados_onda[var].mean()
            desvio = dados_onda[var].std()
            erro_padrao = desvio / np.sqrt(n) if n > 0 else np.nan

            resultados.append({
                'Variavel': var,
                'Onda': f"{onda}ª - masculino",
                'N': n,
                'Media': media,
                'Desvio': desvio,
                'Erro_Padrao': erro_padrao
            })

    return pd.DataFrame(resultados)

# Função modificada para testes
def realizar_testes_masculino(df, variaveis):
    resultados = []

    for var in variaveis:
        # Separar dados por onda
        grupo5 = df[df['Onda'] == 5][var].dropna()
        grupo6 = df[df['Onda'] == 6][var].dropna()
        grupo5 = pd.to_numeric(grupo5, errors='coerce')
        grupo6 = pd.to_numeric(grupo6, errors='coerce')
        try:
            # Teste de Levene para igualdade de variâncias
            levene_stat, levene_p = stats.levene(grupo5, grupo6)
        except:
            levene_stat, levene_p = np.nan, np.nan

        # Cálculos comuns
        n1, n2 = len(grupo5), len(grupo6)
        diff_media = grupo5.mean() - grupo6.mean()

        try:
            # Para variâncias iguais
            gl_equal = n1 + n2 - 2
            s_p = np.sqrt(((n1-1)*grupo5.var() + (n2-1)*grupo6.var()) / (n1+n2-2))
            se_diff_equal = s_p * np.sqrt(1/n1 + 1/n2)
            t_stat_equal = diff_media / se_diff_equal if se_diff_equal != 0 else 0
            p_value_equal = 2 * (1 - stats.t.cdf(abs(t_stat_equal), gl_equal))

            # Para variâncias diferentes (Welch's t-test)
            var1, var2 = grupo5.var(), grupo6.var()
            if var1 == 0 and var2 == 0:
                gl_unequal = gl_equal
                se_diff_unequal = se_diff_equal
                t_stat_unequal = t_stat_equal
                p_value_unequal = p_value_equal
            else:
                gl_unequal = int(((var1/n1 + var2/n2)**2) /
                                (((var1/n1)**2/(n1-1) if n1 > 1 else 0) +
                                 ((var2/n2)**2/(n2-1) if n2 > 1 else 0)))
                se_diff_unequal = np.sqrt(var1/n1 + var2/n2)
                t_stat_unequal = diff_media / se_diff_unequal if se_diff_unequal != 0 else 0
                p_value_unequal = 2 * (1 - stats.t.cdf(abs(t_stat_unequal), gl_unequal))

            # Intervalos de confiança
            t_crit_equal = stats.t.ppf(0.975, gl_equal)
            t_crit_unequal = stats.t.ppf(0.975, gl_unequal)

            # Calcular ICs
            ic_inf_equal = diff_media - t_crit_equal * se_diff_equal
            ic_sup_equal = diff_media + t_crit_equal * se_diff_equal
            ic_inf_unequal = diff_media - t_crit_unequal * se_diff_unequal
            ic_sup_unequal = diff_media + t_crit_unequal * se_diff_unequal

        except:
            # Se houver erro, preencher com NaN
            t_stat_equal = gl_equal = p_value_equal = se_diff_equal = ic_inf_equal = ic_sup_equal = np.nan
            t_stat_unequal = gl_unequal = p_value_unequal = se_diff_unequal = ic_inf_unequal = ic_sup_unequal = np.nan

        # Adicionar resultados para variâncias iguais
        resultados.append({
            'Variavel': var,
            'Tipo': 'Variâncias iguais assumidas',
            'Levene_Z': levene_stat,
            'Levene_Sig': levene_p,
            't': t_stat_equal,
            'df': gl_equal,
            'Sig_2_extremidades': p_value_equal,
            'Diferenca_media': diff_media,
            'Erro_padrao_diferenca': se_diff_equal,
            'IC_95_Inferior': ic_inf_equal,
            'IC_95_Superior': ic_sup_equal
        })

        # Adicionar resultados para variâncias diferentes
        resultados.append({
            'Variavel': var,
            'Tipo': 'Variâncias iguais não assumidas',
            'Levene_Z': None,
            'Levene_Sig': None,
            't': t_stat_unequal,
            'df': gl_unequal,
            'Sig_2_extremidades': p_value_unequal,
            'Diferenca_media': diff_media,
            'Erro_padrao_diferenca': se_diff_unequal,
            'IC_95_Inferior': ic_inf_unequal,
            'IC_95_Superior': ic_sup_unequal
        })

    return pd.DataFrame(resultados)

# Calcular estatísticas e testes
estatisticas_masculino = calcular_estatisticas_masculino(base_masculino, variaveis)
testes_masculino = realizar_testes_masculino(base_masculino, variaveis)

# Salvar em Excel
with pd.ExcelWriter('estatisticas_masculino.xlsx') as writer:
    estatisticas_masculino.to_excel(writer, sheet_name='Estatísticas', index=False)
    testes_masculino.to_excel(writer, sheet_name='Testes', index=False)

# Mostrar primeiros resultados
print("Estatísticas descritivas:")
print(estatisticas_masculino.head())
print("\nTestes:")
print(testes_masculino.head())

<ipython-input-144-3dcbec4a74ca>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_onda[var] = pd.to_numeric(dados_onda[var], errors='coerce')
/usr/local/lib/python3.11/dist-packages/scipy/stats/_morestats.py:3345: RuntimeWarning: invalid value encountered in scalar divide
  W = numer / denom

Estatísticas descritivas:
  Variavel            Onda    N     Media    Desvio  Erro_Padrao
0       F2  5ª - masculino  679  2.000000  0.000000     0.000000
1       F2  6ª - masculino  680  2.000000  0.000000     0.000000
2       F3  5ª - masculino  679  3.166421  1.241012     0.047626
3       F3  6ª - masculino  680  3.230882  1.300703     0.049880
4       F6  5ª - masculino  679  2.670103  1.011806     0.038830

Testes:
  Variavel                             Tipo  Levene_Z  Levene_Sig         t  \
0       F2      Variâncias iguais assumidas       NaN         NaN  0.000000
1       F2  Variâncias iguais não assumidas       NaN         NaN  0.000000
2       F3      Variâncias iguais assumidas  3.846007    0.050069 -0.934660
3       F3  Variâncias iguais não assumidas       NaN         NaN -0.934692
4       F6      Variâncias iguais assumidas  2.485240    0.115152  0.017472

     df  Sig_2_extremidades  Diferenca_media  Erro_padrao_diferenca  \
0  1357            1.000000         0.000000               0.000000
1  1357            1.000000         0.000000               0.000000
2  1357            0.350130        -0.064461               0.068967
3  1354            0.350114        -0.064461               0.068965
4  1357            0.986063         0.000985               0.056402

   IC_95_Inferior  IC_95_Superior
0        0.000000        0.000000
1        0.000000        0.000000
2       -0.199756        0.070833
3       -0.199751        0.070829
4       -0.109659        0.111630

In [145]:
base_filtrada

,P30,ID,UF,F2,F3,F6,P0.1,P0.2,P0.3,P0.4,...,P17.4,P17.5,P17.6,P17.7,P17.8,P17.9,P18.1,P18.2,Peso,Onda
0,1,403,7,1,1,1,4,4,1,5,...,2,1,1,2,<NA>,1,5,3,"0,14",5
1,1,602,9,1,1,1,5,1,1,5,...,1,1,1,1,1,<NA>,4,5,"0,14",5
2,1,516,9,1,1,1,3,2,2,4,...,<NA>,<NA>,1,2,<NA>,2,4,4,"0,14",5
3,1,2927,7,1,1,1,1,1,1,2,...,1,<NA>,1,1,1,<NA>,3,2,"0,14",5
4,2,210,12,1,1,1,1,1,1,4,...,2,2,2,2,1,2,2,2,"0,56",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3025,3,151776882,Goiás,2,1,4,1,1,1,1,...,2,2,1,2,2,1,5,5,2.07,6
3026,1,151776928,Distrito Federal,1,1,2,1,1,1,1,...,NA,1,1,NA,1,2,5,3,0.08,6
3027,1,151777090,Santa Catarina,2,5,4,1,1,1,3,...,2,2,2,2,1,2,5,5,0.1,6
3028,3,151777439,Amapá,2,3,1,2,1,2,3,...,2,NA,1,1,1,NA,4,4,0.31,6
3029,1,151778884,Pará,2,3,1,2,1,1,4,...,1,1,1,1,1,2,5,3,0.04,6

In [146]:
# Dicionário com os grupos e suas descrições


# Modificar a função de estatísticas para incluir a descrição do grupo
def calcular_estatisticas_grupo(df, variaveis, grupo_desc):
    resultados = []

    for var in variaveis:
        for onda in df['Onda'].unique():
            dados_onda = df[df['Onda'] == onda]
            dados_onda[var] = pd.to_numeric(dados_onda[var], errors='coerce')
            n = dados_onda[var].count()
            media = dados_onda[var].mean()
            desvio = dados_onda[var].std()
            erro_padrao = desvio / np.sqrt(n) if n > 0 else np.nan

            resultados.append({
                'Variavel': var,
                'Onda': f"{onda}ª - {grupo_desc}",
                'N': n,
                'Media': media,
                'Desvio': desvio,
                'Erro_Padrao': erro_padrao
            })

    return pd.DataFrame(resultados)



# Criar Excel com uma aba para cada grupo
with pd.ExcelWriter('estatisticas_grupos2.xlsx') as writer:
    # Para cada grupo no dicionário
    for nome_grupo, info_grupo in grupos_analise.items():
        # Filtrar a base para o grupo específico
        base_grupo = base_filtrada[base_filtrada[info_grupo['variavel']] == info_grupo['valor']].copy()

        # Calcular estatísticas e testes
        estatisticas_grupo = calcular_estatisticas_grupo(base_grupo, variaveis, info_grupo['descricao'])
        testes_grupo = realizar_testes_masculino(base_grupo, variaveis)

        # Salvar em abas específicas
        estatisticas_grupo.to_excel(writer, sheet_name=f'Est_{nome_grupo}', index=False)
        testes_grupo.to_excel(writer, sheet_name=f'Test_{nome_grupo}', index=False)

print("Análises concluídas e salvas em 'estatisticas_grupos2.xlsx'")

<ipython-input-146-6f3e9bbd9a01>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_onda[var] = pd.to_numeric(dados_onda[var], errors='coerce')
/usr/local/lib/python3.11/dist-packages/scipy/stats/_morestats.py:3345: RuntimeWarning: invalid value encountered in scalar divide
  W = numer / denom

Análises concluídas e salvas em 'estatisticas_grupos2.xlsx'